### ISSUE TITLE
Fullstack Developer - Pleno - .NET/Javascript - Remoto

### ISSUE THREAD

**Issue by rsantosdev** [AzureBrasil-cloud/vagas#1]
### Nossa empresa
Somos um dos principais parceiros Microsoft no segmento Azure. Especialistas em soluções para reduzir custos de nuvem e aumentar produtividade.

### Descrição da vaga
Estamos buscando um desenvolvedor pleno para nos ajudar a evoluir nosso produto de redução de custos no PowerBI, o [PowerEmbedded](https://powerembedded.com.br/). Você será responsável por implementar novas features e ajudar na evolução do sistema na totalidade.
Maior parte do trabalho é feito no back-end com integrações com as APIs do PowerBI, mas em alguns casos você precisara lidar com o front-end também (asp.net core MVC + jQuery).

### Local
* Remoto

### Requisitos
* .NET Core / C#
* OOP
* O básico sobre docker
* Padrões de projeto
* Pode configurar o ambiente de desenvolvimento sozinho;
* Experiência com JQuery
* Experiência com SQL
* Experiência com EF Core
* Já trabalhou com Asp.net MVC
* Saber interpretar documentações de API e realizar integrações

### Contratação
* Full Time
* PJ: R$8.000,00

### Como Aplicar
Crie um projeto asp.net core que consiga mostrar um relatório do PowerBI utilizando o Embedded Token. Submeta o repositório (e comentários necessários) aqui na issue ou envie um email para rsantos [at] azurebrasil.cloud e iremos avaliar.

Dicas:
* Toda a documentação para gerar o token esta na documentação oficial: https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers?tabs=net-core
* Todo novo usuário de PowerBI tem direito a uma licença Pro para testes por 60 dias.
* Utilize a opção de autenticação "Master User" da documentação.

**Comment by guigovaski** [comment]
Repositorio com o codigo fonte do teste:
- https://github.com/guigovaski/PowerBIEmbedded/tree/main

Projeto rodando no App Service:
- [testepowerembedded.azurewebsites.net](https://testepowerembedded.azurewebsites.net/)

**Comment by rsantosdev** [comment]
Estamos com os candidatos fechados! Se inscrevam no repositório para terem acesso a novas vagas
